export type PhraseCategory = 'greetings' | 'food' | 'transport' | 'emergency' | 'shopping' | 'hotel';

export interface Phrase {
  id: string;
  english: string;
  native: string;
  romanization: string;
}

export interface LanguageData {
  code: string;
  name: string;
  flag: string;
  phrases: Record<PhraseCategory, Phrase[]>;
}

export const CATEGORIES: { key: PhraseCategory; label: string; icon: string }[] = [
  { key: 'greetings', label: 'Greetings', icon: '👋' },
  { key: 'food', label: 'Food', icon: '🍜' },
  { key: 'transport', label: 'Transport', icon: '🚌' },
  { key: 'emergency', label: 'Emergency', icon: '🆘' },
  { key: 'shopping', label: 'Shopping', icon: '🛍️' },
  { key: 'hotel', label: 'Hotel', icon: '🏨' },
];

export const PHRASES_DATA: Record<string, LanguageData> = {
  ja: {
    code: 'ja',
    name: 'Japanese',
    flag: '🇯🇵',
    phrases: {
      greetings: [
        { id: 'ja_g1', english: 'Hello', native: 'こんにちは', romanization: 'Konnichiwa' },
        { id: 'ja_g2', english: 'Good morning', native: 'おはようございます', romanization: 'Ohayou gozaimasu' },
        { id: 'ja_g3', english: 'Good evening', native: 'こんばんは', romanization: 'Konbanwa' },
        { id: 'ja_g4', english: 'Goodbye', native: 'さようなら', romanization: 'Sayounara' },
        { id: 'ja_g5', english: 'Thank you', native: 'ありがとうございます', romanization: 'Arigatou gozaimasu' },
        { id: 'ja_g6', english: 'Please', native: 'おねがいします', romanization: 'Onegai shimasu' },
        { id: 'ja_g7', english: 'Excuse me', native: 'すみません', romanization: 'Sumimasen' },
        { id: 'ja_g8', english: 'I don\'t understand', native: 'わかりません', romanization: 'Wakarimasen' },
      ],
      food: [
        { id: 'ja_f1', english: 'I\'m vegetarian', native: 'ベジタリアンです', romanization: 'Bejitarian desu' },
        { id: 'ja_f2', english: 'No spicy please', native: '辛くしないでください', romanization: 'Karaku shinaide kudasai' },
        { id: 'ja_f3', english: 'The bill please', native: 'お会計をお願いします', romanization: 'Okaikei wo onegai shimasu' },
        { id: 'ja_f4', english: 'This is delicious!', native: 'おいしいです！', romanization: 'Oishii desu!' },
        { id: 'ja_f5', english: 'Water please', native: 'お水をください', romanization: 'Omizu wo kudasai' },
        { id: 'ja_f6', english: 'I\'m allergic to nuts', native: 'ナッツアレルギーがあります', romanization: 'Nattsu arerugii ga arimasu' },
        { id: 'ja_f7', english: 'Do you have an English menu?', native: '英語のメニューはありますか？', romanization: 'Eigo no menyu wa arimasu ka?' },
        { id: 'ja_f8', english: 'One more please', native: 'もう一つください', romanization: 'Mou hitotsu kudasai' },
      ],
      transport: [
        { id: 'ja_t1', english: 'Take me to the airport', native: '空港まで連れて行ってください', romanization: 'Kuukou made tsurete itte kudasai' },
        { id: 'ja_t2', english: 'How much is the fare?', native: '料金はいくらですか？', romanization: 'Ryoukin wa ikura desu ka?' },
        { id: 'ja_t3', english: 'Stop here please', native: 'ここで止めてください', romanization: 'Koko de tomete kudasai' },
        { id: 'ja_t4', english: 'Where is the nearest station?', native: '一番近い駅はどこですか？', romanization: 'Ichiban chikai eki wa doko desu ka?' },
        { id: 'ja_t5', english: 'Is this the train to Tokyo?', native: 'これは東京行きの電車ですか？', romanization: 'Kore wa Tokyo iki no densha desu ka?' },
        { id: 'ja_t6', english: 'I am lost', native: '迷子になりました', romanization: 'Maigo ni narimashita' },
        { id: 'ja_t7', english: 'Turn left', native: '左に曲がってください', romanization: 'Hidari ni magatte kudasai' },
        { id: 'ja_t8', english: 'Turn right', native: '右に曲がってください', romanization: 'Migi ni magatte kudasai' },
      ],
      emergency: [
        { id: 'ja_e1', english: 'Help!', native: '助けて！', romanization: 'Tasukete!' },
        { id: 'ja_e2', english: 'Call the police!', native: '警察を呼んでください！', romanization: 'Keisatsu wo yonde kudasai!' },
        { id: 'ja_e3', english: 'I need a doctor', native: '医者が必要です', romanization: 'Isha ga hitsuyou desu' },
        { id: 'ja_e4', english: 'Where is the hospital?', native: '病院はどこですか？', romanization: 'Byouin wa doko desu ka?' },
        { id: 'ja_e5', english: 'I\'ve been robbed', native: '強盗に遭いました', romanization: 'Goutou ni aimashita' },
        { id: 'ja_e6', english: 'Call an ambulance', native: '救急車を呼んでください', romanization: 'Kyuukyuusha wo yonde kudasai' },
        { id: 'ja_e7', english: 'I\'m having an allergic reaction', native: 'アレルギー反応が出ています', romanization: 'Arerugii hannou ga dete imasu' },
        { id: 'ja_e8', english: 'I need help', native: '助けが必要です', romanization: 'Tasuke ga hitsuyou desu' },
      ],
      shopping: [
        { id: 'ja_s1', english: 'How much is this?', native: 'これはいくらですか？', romanization: 'Kore wa ikura desu ka?' },
        { id: 'ja_s2', english: 'Too expensive', native: '高すぎます', romanization: 'Taka sugimasu' },
        { id: 'ja_s3', english: 'Do you have a smaller size?', native: 'もっと小さいサイズはありますか？', romanization: 'Motto chiisai saizu wa arimasu ka?' },
        { id: 'ja_s4', english: 'I\'ll take this', native: 'これをください', romanization: 'Kore wo kudasai' },
        { id: 'ja_s5', english: 'Can I get a discount?', native: '割引してもらえますか？', romanization: 'Waribiki shite moraemasu ka?' },
        { id: 'ja_s6', english: 'Do you accept credit cards?', native: 'クレジットカードは使えますか？', romanization: 'Kurejitto kaado wa tsukaemasu ka?' },
        { id: 'ja_s7', english: 'Can I try this on?', native: '試着できますか？', romanization: 'Shichaku dekimasu ka?' },
        { id: 'ja_s8', english: 'I\'m just looking', native: '見ているだけです', romanization: 'Mite iru dake desu' },
      ],
      hotel: [
        { id: 'ja_h1', english: 'I have a reservation', native: '予約があります', romanization: 'Yoyaku ga arimasu' },
        { id: 'ja_h2', english: 'What time is check-out?', native: 'チェックアウトは何時ですか？', romanization: 'Chekku auto wa nanji desu ka?' },
        { id: 'ja_h3', english: 'Can I have extra towels?', native: 'タオルを追加でもらえますか？', romanization: 'Taoru wo tsuika de moraemasu ka?' },
        { id: 'ja_h4', english: 'Is breakfast included?', native: '朝食は含まれていますか？', romanization: 'Choushoku wa fukumarete imasu ka?' },
        { id: 'ja_h5', english: 'Do you have WiFi?', native: 'WiFiはありますか？', romanization: 'WiFi wa arimasu ka?' },
        { id: 'ja_h6', english: 'Room service please', native: 'ルームサービスをお願いします', romanization: 'Ruumu saabisu wo onegai shimasu' },
        { id: 'ja_h7', english: 'The air conditioning is broken', native: 'エアコンが壊れています', romanization: 'Eakon ga kowarete imasu' },
        { id: 'ja_h8', english: 'Can you call me a taxi?', native: 'タクシーを呼んでもらえますか？', romanization: 'Takushii wo yonde moraemasu ka?' },
      ],
    },
  },
  ko: {
    code: 'ko',
    name: 'Korean',
    flag: '🇰🇷',
    phrases: {
      greetings: [
        { id: 'ko_g1', english: 'Hello', native: '안녕하세요', romanization: 'Annyeonghaseyo' },
        { id: 'ko_g2', english: 'Good morning', native: '좋은 아침이에요', romanization: 'Joeun achimieyo' },
        { id: 'ko_g3', english: 'Good evening', native: '안녕하세요 (저녁)', romanization: 'Annyeonghaseyo (jeonyeok)' },
        { id: 'ko_g4', english: 'Goodbye', native: '안녕히 가세요', romanization: 'Annyeonghi gaseyo' },
        { id: 'ko_g5', english: 'Thank you', native: '감사합니다', romanization: 'Gamsahamnida' },
        { id: 'ko_g6', english: 'Please', native: '부탁드려요', romanization: 'Butakdeuryeoyo' },
        { id: 'ko_g7', english: 'Excuse me', native: '실례합니다', romanization: 'Sillyehamnida' },
        { id: 'ko_g8', english: 'I don\'t understand', native: '모르겠어요', romanization: 'Moreugeosseoyo' },
      ],
      food: [
        { id: 'ko_f1', english: 'I\'m vegetarian', native: '저는 채식주의자예요', romanization: 'Jeoneun chaesigjuuijayeyo' },
        { id: 'ko_f2', english: 'No spicy please', native: '맵지 않게 해주세요', romanization: 'Maepji anke haejuseyo' },
        { id: 'ko_f3', english: 'The bill please', native: '계산서 주세요', romanization: 'Gyesanseo juseyo' },
        { id: 'ko_f4', english: 'This is delicious!', native: '맛있어요!', romanization: 'Masisseoyo!' },
        { id: 'ko_f5', english: 'Water please', native: '물 주세요', romanization: 'Mul juseyo' },
        { id: 'ko_f6', english: 'I\'m allergic to nuts', native: '견과류 알레르기가 있어요', romanization: 'Gyeongwaryu allereugiга isseoyo' },
        { id: 'ko_f7', english: 'Do you have an English menu?', native: '영어 메뉴판 있어요?', romanization: 'Yeongeo menyupan isseoyo?' },
        { id: 'ko_f8', english: 'One more please', native: '하나 더 주세요', romanization: 'Hana deo juseyo' },
      ],
      transport: [
        { id: 'ko_t1', english: 'Take me to the airport', native: '공항으로 가주세요', romanization: 'Gonghanguro gajuseyo' },
        { id: 'ko_t2', english: 'How much is the fare?', native: '요금이 얼마예요?', romanization: 'Yogeumi eolmayeyo?' },
        { id: 'ko_t3', english: 'Stop here please', native: '여기서 세워주세요', romanization: 'Yeogiseo seowojuseyo' },
        { id: 'ko_t4', english: 'Where is the nearest subway?', native: '가장 가까운 지하철이 어디예요?', romanization: 'Gajang gakkaun jihacheori eodiyeyo?' },
        { id: 'ko_t5', english: 'I am lost', native: '길을 잃었어요', romanization: 'Gireul ireosseoyo' },
        { id: 'ko_t6', english: 'Turn left', native: '왼쪽으로 가세요', romanization: 'Oenjjogeuro gaseyo' },
        { id: 'ko_t7', english: 'Turn right', native: '오른쪽으로 가세요', romanization: 'Oreunjjogeuro gaseyo' },
        { id: 'ko_t8', english: 'How long will it take?', native: '얼마나 걸려요?', romanization: 'Eolmana geollyeoyo?' },
      ],
      emergency: [
        { id: 'ko_e1', english: 'Help!', native: '도와주세요!', romanization: 'Dowajuseyo!' },
        { id: 'ko_e2', english: 'Call the police!', native: '경찰을 불러주세요!', romanization: 'Gyeongchareul bulleohjuseyo!' },
        { id: 'ko_e3', english: 'I need a doctor', native: '의사가 필요해요', romanization: 'Uisaga piryohaeyo' },
        { id: 'ko_e4', english: 'Where is the hospital?', native: '병원이 어디예요?', romanization: 'Byeongwoni eodiyeyo?' },
        { id: 'ko_e5', english: 'I\'ve been robbed', native: '도둑을 맞았어요', romanization: 'Dodugеul majasseoyo' },
        { id: 'ko_e6', english: 'Call an ambulance', native: '구급차를 불러주세요', romanization: 'Gugeupchareul bulleohjuseyo' },
        { id: 'ko_e7', english: 'I need help', native: '도움이 필요해요', romanization: 'Doumi piryohaeyo' },
        { id: 'ko_e8', english: 'Fire!', native: '불이야!', romanization: 'Buriya!' },
      ],
      shopping: [
        { id: 'ko_s1', english: 'How much is this?', native: '이거 얼마예요?', romanization: 'Igeo eolmayeyo?' },
        { id: 'ko_s2', english: 'Too expensive', native: '너무 비싸요', romanization: 'Neomu bissayo' },
        { id: 'ko_s3', english: 'Do you have a smaller size?', native: '더 작은 사이즈 있어요?', romanization: 'Deo jageun saijeu isseoyo?' },
        { id: 'ko_s4', english: 'I\'ll take this', native: '이거 살게요', romanization: 'Igeo salgeyo' },
        { id: 'ko_s5', english: 'Can I get a discount?', native: '할인 해주실 수 있어요?', romanization: 'Harin haejusil su isseoyo?' },
        { id: 'ko_s6', english: 'Do you accept credit cards?', native: '신용카드 돼요?', romanization: 'Sinyongkadeu dwaeyo?' },
        { id: 'ko_s7', english: 'Can I try this on?', native: '입어봐도 돼요?', romanization: 'Ibeobwado dwaeyo?' },
        { id: 'ko_s8', english: 'I\'m just looking', native: '그냥 구경하는 거예요', romanization: 'Geunyang gugyeonghaneun geoyeyo' },
      ],
      hotel: [
        { id: 'ko_h1', english: 'I have a reservation', native: '예약이 있어요', romanization: 'Yeyagi isseoyo' },
        { id: 'ko_h2', english: 'What time is check-out?', native: '체크아웃이 몇 시예요?', romanization: 'Chekeuausi myeot siyeyo?' },
        { id: 'ko_h3', english: 'Can I have extra towels?', native: '수건 더 주실 수 있어요?', romanization: 'Sugeon deo jusil su isseoyo?' },
        { id: 'ko_h4', english: 'Is breakfast included?', native: '아침 식사 포함이에요?', romanization: 'Achim siksa pohamieyo?' },
        { id: 'ko_h5', english: 'Do you have WiFi?', native: '와이파이 있어요?', romanization: 'Waipai isseoyo?' },
        { id: 'ko_h6', english: 'Room service please', native: '룸서비스 부탁드려요', romanization: 'Rumsseobiseu butakdeuryeoyo' },
        { id: 'ko_h7', english: 'Can you call me a taxi?', native: '택시 불러 주실 수 있어요?', romanization: 'Taeksi bulleo jusil su isseoyo?' },
        { id: 'ko_h8', english: 'My room key doesn\'t work', native: '방 열쇠가 안 돼요', romanization: 'Bang yeolsoega an dwaeyo' },
      ],
    },
  },
  th: {
    code: 'th',
    name: 'Thai',
    flag: '🇹🇭',
    phrases: {
      greetings: [
        { id: 'th_g1', english: 'Hello', native: 'สวัสดีครับ/ค่ะ', romanization: 'Sawadee krap/ka' },
        { id: 'th_g2', english: 'Good morning', native: 'อรุณสวัสดิ์', romanization: 'Arun sawat' },
        { id: 'th_g3', english: 'Goodbye', native: 'ลาก่อนครับ/ค่ะ', romanization: 'La gon krap/ka' },
        { id: 'th_g4', english: 'Thank you', native: 'ขอบคุณครับ/ค่ะ', romanization: 'Khob khun krap/ka' },
        { id: 'th_g5', english: 'Please', native: 'กรุณาครับ/ค่ะ', romanization: 'Karuna krap/ka' },
        { id: 'th_g6', english: 'Excuse me', native: 'ขอโทษครับ/ค่ะ', romanization: 'Kho thot krap/ka' },
        { id: 'th_g7', english: 'I don\'t understand', native: 'ไม่เข้าใจครับ/ค่ะ', romanization: 'Mai khao jai krap/ka' },
        { id: 'th_g8', english: 'Do you speak English?', native: 'คุณพูดภาษาอังกฤษได้ไหม?', romanization: 'Khun phut phasa angkrit dai mai?' },
      ],
      food: [
        { id: 'th_f1', english: 'I\'m vegetarian', native: 'ฉันกินมังสวิรัติ', romanization: 'Chan kin mangsawirat' },
        { id: 'th_f2', english: 'Not spicy please', native: 'ไม่เผ็ดนะครับ/ค่ะ', romanization: 'Mai phet na krap/ka' },
        { id: 'th_f3', english: 'The bill please', native: 'เช็คบิลด้วยครับ/ค่ะ', romanization: 'Chek bin duai krap/ka' },
        { id: 'th_f4', english: 'This is delicious!', native: 'อร่อยมากครับ/ค่ะ!', romanization: 'Aroi mak krap/ka!' },
        { id: 'th_f5', english: 'Water please', native: 'น้ำเปล่าครับ/ค่ะ', romanization: 'Nam plao krap/ka' },
        { id: 'th_f6', english: 'No peanuts please', native: 'ไม่ใส่ถั่วลิสงนะครับ/ค่ะ', romanization: 'Mai sai thua lisong na krap/ka' },
        { id: 'th_f7', english: 'What do you recommend?', native: 'คุณแนะนำอะไร?', romanization: 'Khun nae nam arai?' },
        { id: 'th_f8', english: 'One more please', native: 'ขอเพิ่มอีกหนึ่งครับ/ค่ะ', romanization: 'Kho phoem ik nueng krap/ka' },
      ],
      transport: [
        { id: 'th_t1', english: 'Take me to the airport', native: 'ไปสนามบินครับ/ค่ะ', romanization: 'Pai sanam bin krap/ka' },
        { id: 'th_t2', english: 'How much is the fare?', native: 'ราคาเท่าไหร่ครับ/ค่ะ?', romanization: 'Raka thao rai krap/ka?' },
        { id: 'th_t3', english: 'Stop here please', native: 'จอดตรงนี้ครับ/ค่ะ', romanization: 'Chot trong ni krap/ka' },
        { id: 'th_t4', english: 'Where is the BTS station?', native: 'สถานีบีทีเอสอยู่ที่ไหน?', romanization: 'Sathani BTS yu thi nai?' },
        { id: 'th_t5', english: 'I am lost', native: 'ฉันหลงทาง', romanization: 'Chan long thang' },
        { id: 'th_t6', english: 'Turn left', native: 'เลี้ยวซ้าย', romanization: 'Liaeo sai' },
        { id: 'th_t7', english: 'Turn right', native: 'เลี้ยวขวา', romanization: 'Liaeo khwa' },
        { id: 'th_t8', english: 'How far is it?', native: 'ไกลแค่ไหนครับ/ค่ะ?', romanization: 'Klai kae nai krap/ka?' },
      ],
      emergency: [
        { id: 'th_e1', english: 'Help!', native: 'ช่วยด้วย!', romanization: 'Chuai duai!' },
        { id: 'th_e2', english: 'Call the police!', native: 'เรียกตำรวจด้วย!', romanization: 'Riak tamruat duai!' },
        { id: 'th_e3', english: 'I need a doctor', native: 'ฉันต้องการหมอ', romanization: 'Chan tong kan mo' },
        { id: 'th_e4', english: 'Where is the hospital?', native: 'โรงพยาบาลอยู่ที่ไหน?', romanization: 'Rong phayaban yu thi nai?' },
        { id: 'th_e5', english: 'I\'ve been robbed', native: 'ฉันถูกปล้น', romanization: 'Chan thuk plon' },
        { id: 'th_e6', english: 'Call an ambulance', native: 'เรียกรถพยาบาลด้วย', romanization: 'Riak rot phayaban duai' },
        { id: 'th_e7', english: 'I need help', native: 'ฉันต้องการความช่วยเหลือ', romanization: 'Chan tong kan khwam chuai luea' },
        { id: 'th_e8', english: 'Fire!', native: 'ไฟไหม้!', romanization: 'Fai mai!' },
      ],
      shopping: [
        { id: 'th_s1', english: 'How much is this?', native: 'อันนี้ราคาเท่าไหร่?', romanization: 'An ni raka thao rai?' },
        { id: 'th_s2', english: 'Too expensive', native: 'แพงเกินไป', romanization: 'Phaeng koen pai' },
        { id: 'th_s3', english: 'Can you give a discount?', native: 'ลดราคาได้ไหม?', romanization: 'Lot raka dai mai?' },
        { id: 'th_s4', english: 'I\'ll take this', native: 'เอาอันนี้', romanization: 'Ao an ni' },
        { id: 'th_s5', english: 'Do you accept credit cards?', native: 'รับบัตรเครดิตไหม?', romanization: 'Rap bat khredit mai?' },
        { id: 'th_s6', english: 'Can I try this on?', native: 'ลองได้ไหม?', romanization: 'Long dai mai?' },
        { id: 'th_s7', english: 'I\'m just looking', native: 'ดูเล่นๆ ครับ/ค่ะ', romanization: 'Du len len krap/ka' },
        { id: 'th_s8', english: 'Do you have this in another color?', native: 'มีสีอื่นไหม?', romanization: 'Mi si uen mai?' },
      ],
      hotel: [
        { id: 'th_h1', english: 'I have a reservation', native: 'ฉันมีการจอง', romanization: 'Chan mi kan chong' },
        { id: 'th_h2', english: 'What time is check-out?', native: 'เช็คเอ้าต์กี่โมง?', romanization: 'Chek ao ki mong?' },
        { id: 'th_h3', english: 'Can I have extra towels?', native: 'ขอผ้าเช็ดตัวเพิ่มได้ไหม?', romanization: 'Kho pha chet tua phoem dai mai?' },
        { id: 'th_h4', english: 'Is breakfast included?', native: 'รวมอาหารเช้าไหม?', romanization: 'Ruam ahan chao mai?' },
        { id: 'th_h5', english: 'Do you have WiFi?', native: 'มีไวไฟไหม?', romanization: 'Mi wifi mai?' },
        { id: 'th_h6', english: 'Room service please', native: 'รูมเซอร์วิสครับ/ค่ะ', romanization: 'Rum soewit krap/ka' },
        { id: 'th_h7', english: 'Can you call me a taxi?', native: 'ช่วยเรียกแท็กซี่ให้หน่อยได้ไหม?', romanization: 'Chuai riak thaeksi hai noi dai mai?' },
        { id: 'th_h8', english: 'The air conditioning is broken', native: 'แอร์เสียครับ/ค่ะ', romanization: 'Ae sia krap/ka' },
      ],
    },
  },
  vi: {
    code: 'vi',
    name: 'Vietnamese',
    flag: '🇻🇳',
    phrases: {
      greetings: [
        { id: 'vi_g1', english: 'Hello', native: 'Xin chào', romanization: 'Sin chao' },
        { id: 'vi_g2', english: 'Good morning', native: 'Chào buổi sáng', romanization: 'Chao buoi sang' },
        { id: 'vi_g3', english: 'Goodbye', native: 'Tạm biệt', romanization: 'Tam biet' },
        { id: 'vi_g4', english: 'Thank you', native: 'Cảm ơn', romanization: 'Cam on' },
        { id: 'vi_g5', english: 'Please', native: 'Làm ơn', romanization: 'Lam on' },
        { id: 'vi_g6', english: 'Excuse me', native: 'Xin lỗi', romanization: 'Sin loi' },
        { id: 'vi_g7', english: 'I don\'t understand', native: 'Tôi không hiểu', romanization: 'Toi khong hieu' },
        { id: 'vi_g8', english: 'Do you speak English?', native: 'Bạn có nói tiếng Anh không?', romanization: 'Ban co noi tieng Anh khong?' },
      ],
      food: [
        { id: 'vi_f1', english: 'I\'m vegetarian', native: 'Tôi ăn chay', romanization: 'Toi an chay' },
        { id: 'vi_f2', english: 'Not spicy please', native: 'Không cay nhé', romanization: 'Khong cay nhe' },
        { id: 'vi_f3', english: 'The bill please', native: 'Tính tiền giúp tôi', romanization: 'Tinh tien giup toi' },
        { id: 'vi_f4', english: 'This is delicious!', native: 'Ngon lắm!', romanization: 'Ngon lam!' },
        { id: 'vi_f5', english: 'Water please', native: 'Cho tôi nước', romanization: 'Cho toi nuoc' },
        { id: 'vi_f6', english: 'I\'m allergic to shrimp', native: 'Tôi bị dị ứng tôm', romanization: 'Toi bi di ung tom' },
        { id: 'vi_f7', english: 'One bowl of pho please', native: 'Cho tôi một bát phở', romanization: 'Cho toi mot bat pho' },
        { id: 'vi_f8', english: 'One more please', native: 'Thêm một cái nữa', romanization: 'Them mot cai nua' },
      ],
      transport: [
        { id: 'vi_t1', english: 'Take me to the airport', native: 'Đưa tôi đến sân bay', romanization: 'Dua toi den san bay' },
        { id: 'vi_t2', english: 'How much is the fare?', native: 'Giá bao nhiêu?', romanization: 'Gia bao nhieu?' },
        { id: 'vi_t3', english: 'Stop here please', native: 'Dừng ở đây', romanization: 'Dung o day' },
        { id: 'vi_t4', english: 'Where is the bus stop?', native: 'Trạm xe buýt ở đâu?', romanization: 'Tram xe buyt o dau?' },
        { id: 'vi_t5', english: 'I am lost', native: 'Tôi bị lạc', romanization: 'Toi bi lac' },
        { id: 'vi_t6', english: 'Turn left', native: 'Rẽ trái', romanization: 'Re trai' },
        { id: 'vi_t7', english: 'Turn right', native: 'Rẽ phải', romanization: 'Re phai' },
        { id: 'vi_t8', english: 'Straight ahead', native: 'Đi thẳng', romanization: 'Di thang' },
      ],
      emergency: [
        { id: 'vi_e1', english: 'Help!', native: 'Cứu tôi với!', romanization: 'Cuu toi voi!' },
        { id: 'vi_e2', english: 'Call the police!', native: 'Gọi cảnh sát!', romanization: 'Goi canh sat!' },
        { id: 'vi_e3', english: 'I need a doctor', native: 'Tôi cần bác sĩ', romanization: 'Toi can bac si' },
        { id: 'vi_e4', english: 'Where is the hospital?', native: 'Bệnh viện ở đâu?', romanization: 'Benh vien o dau?' },
        { id: 'vi_e5', english: 'I\'ve been robbed', native: 'Tôi bị cướp', romanization: 'Toi bi cuop' },
        { id: 'vi_e6', english: 'Call an ambulance', native: 'Gọi xe cứu thương', romanization: 'Goi xe cuu thuong' },
        { id: 'vi_e7', english: 'I need help', native: 'Tôi cần giúp đỡ', romanization: 'Toi can giup do' },
        { id: 'vi_e8', english: 'Fire!', native: 'Cháy!', romanization: 'Chay!' },
      ],
      shopping: [
        { id: 'vi_s1', english: 'How much is this?', native: 'Cái này giá bao nhiêu?', romanization: 'Cai nay gia bao nhieu?' },
        { id: 'vi_s2', english: 'Too expensive', native: 'Đắt quá', romanization: 'Dat qua' },
        { id: 'vi_s3', english: 'Can you give a discount?', native: 'Giảm giá được không?', romanization: 'Giam gia duoc khong?' },
        { id: 'vi_s4', english: 'I\'ll take this', native: 'Tôi lấy cái này', romanization: 'Toi lay cai nay' },
        { id: 'vi_s5', english: 'Do you accept credit cards?', native: 'Có nhận thẻ tín dụng không?', romanization: 'Co nhan the tin dung khong?' },
        { id: 'vi_s6', english: 'I\'m just looking', native: 'Tôi chỉ xem thôi', romanization: 'Toi chi xem thoi' },
        { id: 'vi_s7', english: 'Do you have a smaller size?', native: 'Có size nhỏ hơn không?', romanization: 'Co size nho hon khong?' },
        { id: 'vi_s8', english: 'Can I try this on?', native: 'Tôi có thể thử không?', romanization: 'Toi co the thu khong?' },
      ],
      hotel: [
        { id: 'vi_h1', english: 'I have a reservation', native: 'Tôi có đặt phòng', romanization: 'Toi co dat phong' },
        { id: 'vi_h2', english: 'What time is check-out?', native: 'Mấy giờ trả phòng?', romanization: 'May gio tra phong?' },
        { id: 'vi_h3', english: 'Can I have extra towels?', native: 'Cho tôi thêm khăn tắm', romanization: 'Cho toi them khan tam' },
        { id: 'vi_h4', english: 'Is breakfast included?', native: 'Có bao gồm bữa sáng không?', romanization: 'Co bao gom bua sang khong?' },
        { id: 'vi_h5', english: 'Do you have WiFi?', native: 'Có WiFi không?', romanization: 'Co WiFi khong?' },
        { id: 'vi_h6', english: 'Room service please', native: 'Phục vụ phòng', romanization: 'Phuc vu phong' },
        { id: 'vi_h7', english: 'Can you call me a taxi?', native: 'Gọi taxi giúp tôi được không?', romanization: 'Goi taxi giup toi duoc khong?' },
        { id: 'vi_h8', english: 'The shower is broken', native: 'Vòi hoa sen bị hỏng', romanization: 'Voi hoa sen bi hong' },
      ],
    },
  },
  es: {
    code: 'es',
    name: 'Spanish',
    flag: '🇪🇸',
    phrases: {
      greetings: [
        { id: 'es_g1', english: 'Hello', native: 'Hola', romanization: 'Hola' },
        { id: 'es_g2', english: 'Good morning', native: 'Buenos días', romanization: 'Bwenos dee-as' },
        { id: 'es_g3', english: 'Good evening', native: 'Buenas noches', romanization: 'Bwenas no-ches' },
        { id: 'es_g4', english: 'Goodbye', native: 'Adiós', romanization: 'A-dee-os' },
        { id: 'es_g5', english: 'Thank you', native: 'Gracias', romanization: 'Gra-see-as' },
        { id: 'es_g6', english: 'Please', native: 'Por favor', romanization: 'Por fa-vor' },
        { id: 'es_g7', english: 'Excuse me', native: 'Disculpe', romanization: 'Dis-kul-pe' },
        { id: 'es_g8', english: 'I don\'t understand', native: 'No entiendo', romanization: 'No en-tyen-do' },
      ],
      food: [
        { id: 'es_f1', english: 'I\'m vegetarian', native: 'Soy vegetariano/a', romanization: 'Soy ve-he-ta-ree-a-no/a' },
        { id: 'es_f2', english: 'Not spicy please', native: 'Sin picante, por favor', romanization: 'Sin pi-kan-te, por fa-vor' },
        { id: 'es_f3', english: 'The bill please', native: 'La cuenta, por favor', romanization: 'La kwen-ta, por fa-vor' },
        { id: 'es_f4', english: 'This is delicious!', native: '¡Está delicioso!', romanization: 'Es-ta de-li-syoso!' },
        { id: 'es_f5', english: 'Water please', native: 'Agua, por favor', romanization: 'A-gwa, por fa-vor' },
        { id: 'es_f6', english: 'I\'m allergic to gluten', native: 'Soy alérgico/a al gluten', romanization: 'Soy a-ler-hi-ko al glu-ten' },
        { id: 'es_f7', english: 'What do you recommend?', native: '¿Qué recomienda?', romanization: 'Ke re-ko-myen-da?' },
        { id: 'es_f8', english: 'One more please', native: 'Uno más, por favor', romanization: 'Uno mas, por fa-vor' },
      ],
      transport: [
        { id: 'es_t1', english: 'Take me to the airport', native: 'Lléveme al aeropuerto', romanization: 'Yeve-me al ae-ro-pwer-to' },
        { id: 'es_t2', english: 'How much is the fare?', native: '¿Cuánto cuesta el pasaje?', romanization: 'Kwan-to kwes-ta el pa-sa-he?' },
        { id: 'es_t3', english: 'Stop here please', native: 'Pare aquí, por favor', romanization: 'Pa-re a-ki, por fa-vor' },
        { id: 'es_t4', english: 'Where is the metro?', native: '¿Dónde está el metro?', romanization: 'Don-de es-ta el me-tro?' },
        { id: 'es_t5', english: 'I am lost', native: 'Estoy perdido/a', romanization: 'Es-toy per-di-do/a' },
        { id: 'es_t6', english: 'Turn left', native: 'Gire a la izquierda', romanization: 'Hi-re a la is-kyer-da' },
        { id: 'es_t7', english: 'Turn right', native: 'Gire a la derecha', romanization: 'Hi-re a la de-re-cha' },
        { id: 'es_t8', english: 'Straight ahead', native: 'Todo recto', romanization: 'To-do rek-to' },
      ],
      emergency: [
        { id: 'es_e1', english: 'Help!', native: '¡Ayuda!', romanization: 'A-yu-da!' },
        { id: 'es_e2', english: 'Call the police!', native: '¡Llame a la policía!', romanization: 'Ya-me a la po-li-see-a!' },
        { id: 'es_e3', english: 'I need a doctor', native: 'Necesito un médico', romanization: 'Ne-se-si-to un me-di-ko' },
        { id: 'es_e4', english: 'Where is the hospital?', native: '¿Dónde está el hospital?', romanization: 'Don-de es-ta el os-pi-tal?' },
        { id: 'es_e5', english: 'I\'ve been robbed', native: 'Me han robado', romanization: 'Me an ro-ba-do' },
        { id: 'es_e6', english: 'Call an ambulance', native: 'Llame a una ambulancia', romanization: 'Ya-me a una am-bu-lan-sya' },
        { id: 'es_e7', english: 'I need help', native: 'Necesito ayuda', romanization: 'Ne-se-si-to a-yu-da' },
        { id: 'es_e8', english: 'Fire!', native: '¡Fuego!', romanization: 'Fwe-go!' },
      ],
      shopping: [
        { id: 'es_s1', english: 'How much is this?', native: '¿Cuánto cuesta esto?', romanization: 'Kwan-to kwes-ta es-to?' },
        { id: 'es_s2', english: 'Too expensive', native: 'Es muy caro', romanization: 'Es muy ka-ro' },
        { id: 'es_s3', english: 'Can you give a discount?', native: '¿Me puede hacer un descuento?', romanization: 'Me pwe-de a-ser un des-kwen-to?' },
        { id: 'es_s4', english: 'I\'ll take this', native: 'Me llevo esto', romanization: 'Me ye-vo es-to' },
        { id: 'es_s5', english: 'Do you accept credit cards?', native: '¿Aceptan tarjetas de crédito?', romanization: 'A-sep-tan tar-he-tas de kre-di-to?' },
        { id: 'es_s6', english: 'I\'m just looking', native: 'Solo estoy mirando', romanization: 'So-lo es-toy mi-ran-do' },
        { id: 'es_s7', english: 'Can I try this on?', native: '¿Puedo probármelo?', romanization: 'Pwe-do pro-bar-me-lo?' },
        { id: 'es_s8', english: 'Do you have a bigger size?', native: '¿Tiene una talla más grande?', romanization: 'Tye-ne una ta-ya mas gran-de?' },
      ],
      hotel: [
        { id: 'es_h1', english: 'I have a reservation', native: 'Tengo una reserva', romanization: 'Ten-go una re-ser-va' },
        { id: 'es_h2', english: 'What time is check-out?', native: '¿A qué hora es el check-out?', romanization: 'A ke o-ra es el check-out?' },
        { id: 'es_h3', english: 'Can I have extra towels?', native: '¿Me puede dar más toallas?', romanization: 'Me pwe-de dar mas to-a-yas?' },
        { id: 'es_h4', english: 'Is breakfast included?', native: '¿Está incluido el desayuno?', romanization: 'Es-ta in-klwi-do el de-sa-yu-no?' },
        { id: 'es_h5', english: 'Do you have WiFi?', native: '¿Tiene WiFi?', romanization: 'Tye-ne WiFi?' },
        { id: 'es_h6', english: 'Room service please', native: 'Servicio de habitación, por favor', romanization: 'Ser-vi-syo de a-bi-ta-syon, por fa-vor' },
        { id: 'es_h7', english: 'Can you call me a taxi?', native: '¿Puede llamarme un taxi?', romanization: 'Pwe-de ya-mar-me un tak-si?' },
        { id: 'es_h8', english: 'Late check-out please', native: 'Check-out tardío, por favor', romanization: 'Check-out tar-di-o, por fa-vor' },
      ],
    },
  },
  fr: {
    code: 'fr',
    name: 'French',
    flag: '🇫🇷',
    phrases: {
      greetings: [
        { id: 'fr_g1', english: 'Hello', native: 'Bonjour', romanization: 'Bon-zhoor' },
        { id: 'fr_g2', english: 'Good morning', native: 'Bonjour', romanization: 'Bon-zhoor' },
        { id: 'fr_g3', english: 'Good evening', native: 'Bonsoir', romanization: 'Bon-swah' },
        { id: 'fr_g4', english: 'Goodbye', native: 'Au revoir', romanization: 'Oh reh-vwah' },
        { id: 'fr_g5', english: 'Thank you', native: 'Merci', romanization: 'Mehr-see' },
        { id: 'fr_g6', english: 'Please', native: 'S\'il vous plaît', romanization: 'Seel voo play' },
        { id: 'fr_g7', english: 'Excuse me', native: 'Excusez-moi', romanization: 'Eks-kyoo-zay mwah' },
        { id: 'fr_g8', english: 'I don\'t understand', native: 'Je ne comprends pas', romanization: 'Zhuh nuh kom-pron pah' },
      ],
      food: [
        { id: 'fr_f1', english: 'I\'m vegetarian', native: 'Je suis végétarien/végétarienne', romanization: 'Zhuh swee ve-zhay-ta-ryen' },
        { id: 'fr_f2', english: 'Not spicy please', native: 'Pas épicé, s\'il vous plaît', romanization: 'Pah ay-pee-say, seel voo play' },
        { id: 'fr_f3', english: 'The bill please', native: 'L\'addition, s\'il vous plaît', romanization: 'La-di-syon, seel voo play' },
        { id: 'fr_f4', english: 'This is delicious!', native: 'C\'est délicieux!', romanization: 'Say day-lee-syuh!' },
        { id: 'fr_f5', english: 'Water please', native: 'De l\'eau, s\'il vous plaît', romanization: 'Duh loh, seel voo play' },
        { id: 'fr_f6', english: 'I\'m allergic to dairy', native: 'Je suis allergique aux produits laitiers', romanization: 'Zhuh swee a-lehr-zheek oh pro-dwee lay-tyay' },
        { id: 'fr_f7', english: 'What do you recommend?', native: 'Qu\'est-ce que vous recommandez?', romanization: 'Kes kuh voo reh-ko-mon-day?' },
        { id: 'fr_f8', english: 'One more please', native: 'Un de plus, s\'il vous plaît', romanization: 'Un duh ploo, seel voo play' },
      ],
      transport: [
        { id: 'fr_t1', english: 'Take me to the airport', native: 'Conduisez-moi à l\'aéroport', romanization: 'Kon-dwee-zay mwah ah lay-ro-por' },
        { id: 'fr_t2', english: 'How much is the fare?', native: 'Combien coûte le trajet?', romanization: 'Kom-byan koot luh tra-zhay?' },
        { id: 'fr_t3', english: 'Stop here please', native: 'Arrêtez-vous ici, s\'il vous plaît', romanization: 'A-reh-tay voo ee-see, seel voo play' },
        { id: 'fr_t4', english: 'Where is the metro?', native: 'Où est le métro?', romanization: 'Oo ay luh may-tro?' },
        { id: 'fr_t5', english: 'I am lost', native: 'Je suis perdu/e', romanization: 'Zhuh swee pehr-doo' },
        { id: 'fr_t6', english: 'Turn left', native: 'Tournez à gauche', romanization: 'Toor-nay ah gohsh' },
        { id: 'fr_t7', english: 'Turn right', native: 'Tournez à droite', romanization: 'Toor-nay ah drwaht' },
        { id: 'fr_t8', english: 'Straight ahead', native: 'Tout droit', romanization: 'Too drwah' },
      ],
      emergency: [
        { id: 'fr_e1', english: 'Help!', native: 'Au secours!', romanization: 'Oh suh-koor!' },
        { id: 'fr_e2', english: 'Call the police!', native: 'Appelez la police!', romanization: 'A-puh-lay la po-lees!' },
        { id: 'fr_e3', english: 'I need a doctor', native: 'J\'ai besoin d\'un médecin', romanization: 'Zhay buh-zwan dun mayd-san' },
        { id: 'fr_e4', english: 'Where is the hospital?', native: 'Où est l\'hôpital?', romanization: 'Oo ay lo-pee-tal?' },
        { id: 'fr_e5', english: 'I\'ve been robbed', native: 'J\'ai été volé/e', romanization: 'Zhay ay-tay vo-lay' },
        { id: 'fr_e6', english: 'Call an ambulance', native: 'Appelez une ambulance', romanization: 'A-puh-lay oon am-boo-lons' },
        { id: 'fr_e7', english: 'I need help', native: 'J\'ai besoin d\'aide', romanization: 'Zhay buh-zwan dayd' },
        { id: 'fr_e8', english: 'Fire!', native: 'Au feu!', romanization: 'Oh fuh!' },
      ],
      shopping: [
        { id: 'fr_s1', english: 'How much is this?', native: 'Combien ça coûte?', romanization: 'Kom-byan sah koot?' },
        { id: 'fr_s2', english: 'Too expensive', native: 'C\'est trop cher', romanization: 'Say troh shehr' },
        { id: 'fr_s3', english: 'Can you give a discount?', native: 'Pouvez-vous faire une réduction?', romanization: 'Poo-vay voo fehr oon ray-dook-syon?' },
        { id: 'fr_s4', english: 'I\'ll take this', native: 'Je prends ça', romanization: 'Zhuh pron sah' },
        { id: 'fr_s5', english: 'Do you accept credit cards?', native: 'Acceptez-vous les cartes de crédit?', romanization: 'Ak-sep-tay voo lay kart duh kray-dee?' },
        { id: 'fr_s6', english: 'I\'m just looking', native: 'Je regarde seulement', romanization: 'Zhuh ruh-gard suhl-mon' },
        { id: 'fr_s7', english: 'Can I try this on?', native: 'Puis-je l\'essayer?', romanization: 'Pwee-zhuh les-say-yay?' },
        { id: 'fr_s8', english: 'Do you have a smaller size?', native: 'Avez-vous une taille plus petite?', romanization: 'A-vay voo oon tie ploo puh-teet?' },
      ],
      hotel: [
        { id: 'fr_h1', english: 'I have a reservation', native: 'J\'ai une réservation', romanization: 'Zhay oon ray-zer-va-syon' },
        { id: 'fr_h2', english: 'What time is check-out?', native: 'À quelle heure est le départ?', romanization: 'Ah kel uhr ay luh day-par?' },
        { id: 'fr_h3', english: 'Can I have extra towels?', native: 'Puis-je avoir des serviettes supplémentaires?', romanization: 'Pwee-zhuh a-vwahr day sehr-vyet soo-play-mon-tehr?' },
        { id: 'fr_h4', english: 'Is breakfast included?', native: 'Le petit-déjeuner est-il inclus?', romanization: 'Luh puh-tee day-zhuh-nay ay teel an-kloo?' },
        { id: 'fr_h5', english: 'Do you have WiFi?', native: 'Avez-vous le WiFi?', romanization: 'A-vay voo luh WiFi?' },
        { id: 'fr_h6', english: 'Room service please', native: 'Service en chambre, s\'il vous plaît', romanization: 'Sehr-vees on shom-bruh, seel voo play' },
        { id: 'fr_h7', english: 'Can you call me a taxi?', native: 'Pouvez-vous m\'appeler un taxi?', romanization: 'Poo-vay voo ma-play un tak-see?' },
        { id: 'fr_h8', english: 'My room is too noisy', native: 'Ma chambre est trop bruyante', romanization: 'Mah shom-bruh ay troh brwee-yont' },
      ],
    },
  },
  id: {
    code: 'id',
    name: 'Indonesian',
    flag: '🇮🇩',
    phrases: {
      greetings: [
        { id: 'id_g1', english: 'Hello', native: 'Halo', romanization: 'Halo' },
        { id: 'id_g2', english: 'Good morning', native: 'Selamat pagi', romanization: 'Selamat pagi' },
        { id: 'id_g3', english: 'Good evening', native: 'Selamat malam', romanization: 'Selamat malam' },
        { id: 'id_g4', english: 'Goodbye', native: 'Selamat tinggal', romanization: 'Selamat tinggal' },
        { id: 'id_g5', english: 'Thank you', native: 'Terima kasih', romanization: 'Terima kasih' },
        { id: 'id_g6', english: 'Please', native: 'Tolong', romanization: 'Tolong' },
        { id: 'id_g7', english: 'Excuse me', native: 'Permisi', romanization: 'Permisi' },
        { id: 'id_g8', english: 'I don\'t understand', native: 'Saya tidak mengerti', romanization: 'Saya tidak mengerti' },
      ],
      food: [
        { id: 'id_f1', english: 'I\'m vegetarian', native: 'Saya vegetarian', romanization: 'Saya vegetarian' },
        { id: 'id_f2', english: 'Not spicy please', native: 'Jangan pedas', romanization: 'Jangan pedas' },
        { id: 'id_f3', english: 'The bill please', native: 'Minta bonnya', romanization: 'Minta bonnya' },
        { id: 'id_f4', english: 'This is delicious!', native: 'Enak sekali!', romanization: 'Enak sekali!' },
        { id: 'id_f5', english: 'Water please', native: 'Air putih', romanization: 'Air putih' },
        { id: 'id_f6', english: 'No MSG please', native: 'Jangan pakai MSG', romanization: 'Jangan pakai MSG' },
        { id: 'id_f7', english: 'What do you recommend?', native: 'Apa yang direkomendasikan?', romanization: 'Apa yang direkomendasikan?' },
        { id: 'id_f8', english: 'One more please', native: 'Satu lagi', romanization: 'Satu lagi' },
      ],
      transport: [
        { id: 'id_t1', english: 'Take me to the airport', native: 'Antar saya ke bandara', romanization: 'Antar saya ke bandara' },
        { id: 'id_t2', english: 'How much is the fare?', native: 'Berapa ongkosnya?', romanization: 'Berapa ongkosnya?' },
        { id: 'id_t3', english: 'Stop here please', native: 'Berhenti di sini', romanization: 'Berhenti di sini' },
        { id: 'id_t4', english: 'Where is the bus stop?', native: 'Di mana halte bus?', romanization: 'Di mana halte bus?' },
        { id: 'id_t5', english: 'I am lost', native: 'Saya tersesat', romanization: 'Saya tersesat' },
        { id: 'id_t6', english: 'Turn left', native: 'Belok kiri', romanization: 'Belok kiri' },
        { id: 'id_t7', english: 'Turn right', native: 'Belok kanan', romanization: 'Belok kanan' },
        { id: 'id_t8', english: 'Straight ahead', native: 'Lurus terus', romanization: 'Lurus terus' },
      ],
      emergency: [
        { id: 'id_e1', english: 'Help!', native: 'Tolong!', romanization: 'Tolong!' },
        { id: 'id_e2', english: 'Call the police!', native: 'Panggil polisi!', romanization: 'Panggil polisi!' },
        { id: 'id_e3', english: 'I need a doctor', native: 'Saya butuh dokter', romanization: 'Saya butuh dokter' },
        { id: 'id_e4', english: 'Where is the hospital?', native: 'Di mana rumah sakit?', romanization: 'Di mana rumah sakit?' },
        { id: 'id_e5', english: 'I\'ve been robbed', native: 'Saya dirampok', romanization: 'Saya dirampok' },
        { id: 'id_e6', english: 'Call an ambulance', native: 'Panggil ambulans', romanization: 'Panggil ambulans' },
        { id: 'id_e7', english: 'I need help', native: 'Saya butuh bantuan', romanization: 'Saya butuh bantuan' },
        { id: 'id_e8', english: 'Fire!', native: 'Kebakaran!', romanization: 'Kebakaran!' },
      ],
      shopping: [
        { id: 'id_s1', english: 'How much is this?', native: 'Berapa harganya?', romanization: 'Berapa harganya?' },
        { id: 'id_s2', english: 'Too expensive', native: 'Terlalu mahal', romanization: 'Terlalu mahal' },
        { id: 'id_s3', english: 'Can you give a discount?', native: 'Bisa kurang?', romanization: 'Bisa kurang?' },
        { id: 'id_s4', english: 'I\'ll take this', native: 'Saya ambil ini', romanization: 'Saya ambil ini' },
        { id: 'id_s5', english: 'Do you accept credit cards?', native: 'Terima kartu kredit?', romanization: 'Terima kartu kredit?' },
        { id: 'id_s6', english: 'I\'m just looking', native: 'Lihat-lihat dulu', romanization: 'Lihat-lihat dulu' },
        { id: 'id_s7', english: 'Can I try this on?', native: 'Boleh coba?', romanization: 'Boleh coba?' },
        { id: 'id_s8', english: 'Do you have another color?', native: 'Ada warna lain?', romanization: 'Ada warna lain?' },
      ],
      hotel: [
        { id: 'id_h1', english: 'I have a reservation', native: 'Saya punya reservasi', romanization: 'Saya punya reservasi' },
        { id: 'id_h2', english: 'What time is check-out?', native: 'Jam berapa check-out?', romanization: 'Jam berapa check-out?' },
        { id: 'id_h3', english: 'Can I have extra towels?', native: 'Minta handuk tambahan', romanization: 'Minta handuk tambahan' },
        { id: 'id_h4', english: 'Is breakfast included?', native: 'Termasuk sarapan?', romanization: 'Termasuk sarapan?' },
        { id: 'id_h5', english: 'Do you have WiFi?', native: 'Ada WiFi?', romanization: 'Ada WiFi?' },
        { id: 'id_h6', english: 'Room service please', native: 'Layanan kamar', romanization: 'Layanan kamar' },
        { id: 'id_h7', english: 'Can you call me a taxi?', native: 'Tolong panggil taksi', romanization: 'Tolong panggil taksi' },
        { id: 'id_h8', english: 'Late check-out please', native: 'Check-out terlambat', romanization: 'Check-out terlambat' },
      ],
    },
  },
  zh: {
    code: 'zh',
    name: 'Mandarin',
    flag: '🇨🇳',
    phrases: {
      greetings: [
        { id: 'zh_g1', english: 'Hello', native: '你好', romanization: 'Nǐ hǎo' },
        { id: 'zh_g2', english: 'Good morning', native: '早上好', romanization: 'Zǎoshang hǎo' },
        { id: 'zh_g3', english: 'Good evening', native: '晚上好', romanization: 'Wǎnshàng hǎo' },
        { id: 'zh_g4', english: 'Goodbye', native: '再见', romanization: 'Zài jiàn' },
        { id: 'zh_g5', english: 'Thank you', native: '谢谢你', romanization: 'Xièxiè nǐ' },
        { id: 'zh_g6', english: 'Please', native: '请', romanization: 'Qǐng' },
        { id: 'zh_g7', english: 'Excuse me', native: '不好意思', romanization: 'Bù hǎoyìsi' },
        { id: 'zh_g8', english: 'I don\'t understand', native: '我不明白', romanization: 'Wǒ bù míngbái' },
      ],
      food: [
        { id: 'zh_f1', english: 'I\'m vegetarian', native: '我吃素', romanization: 'Wǒ chī sù' },
        { id: 'zh_f2', english: 'Not spicy please', native: '不要辣', romanization: 'Bú yào là' },
        { id: 'zh_f3', english: 'The bill please', native: '买单', romanization: 'Mǎi dān' },
        { id: 'zh_f4', english: 'This is delicious!', native: '很好吃！', romanization: 'Hěn hǎochī!' },
        { id: 'zh_f5', english: 'Water please', native: '请给我水', romanization: 'Qǐng gěi wǒ shuǐ' },
        { id: 'zh_f6', english: 'I\'m allergic to peanuts', native: '我对花生过敏', romanization: 'Wǒ duì huāshēng guòmǐn' },
        { id: 'zh_f7', english: 'What do you recommend?', native: '你推荐什么?', romanization: 'Nǐ tuījiàn shénme?' },
        { id: 'zh_f8', english: 'One more please', native: '再来一个', romanization: 'Zài lái yīgè' },
      ],
      transport: [
        { id: 'zh_t1', english: 'Take me to the airport', native: '送我去机场', romanization: 'Sòng wǒ qù jīchǎng' },
        { id: 'zh_t2', english: 'How much is the fare?', native: '多少钱?', romanization: 'Duōshǎo qián?' },
        { id: 'zh_t3', english: 'Stop here please', native: '在这里停下', romanization: 'Zài zhèlǐ tíng xià' },
        { id: 'zh_t4', english: 'Where is the subway?', native: '地铁在哪里?', romanization: 'Dìtiě zài nǎlǐ?' },
        { id: 'zh_t5', english: 'I am lost', native: '我迷路了', romanization: 'Wǒ mílù le' },
        { id: 'zh_t6', english: 'Turn left', native: '向左转', romanization: 'Xiàng zuǒ zhuǎn' },
        { id: 'zh_t7', english: 'Turn right', native: '向右转', romanization: 'Xiàng yòu zhuǎn' },
        { id: 'zh_t8', english: 'Straight ahead', native: '直走', romanization: 'Zhí zǒu' },
      ],
      emergency: [
        { id: 'zh_e1', english: 'Help!', native: '救命！', romanization: 'Jiùmìng!' },
        { id: 'zh_e2', english: 'Call the police!', native: '报警！', romanization: 'Bào jǐng!' },
        { id: 'zh_e3', english: 'I need a doctor', native: '我需要医生', romanization: 'Wǒ xūyào yīshēng' },
        { id: 'zh_e4', english: 'Where is the hospital?', native: '医院在哪里?', romanization: 'Yīyuàn zài nǎlǐ?' },
        { id: 'zh_e5', english: 'I\'ve been robbed', native: '我被抢劫了', romanization: 'Wǒ bèi qiǎngjié le' },
        { id: 'zh_e6', english: 'Call an ambulance', native: '叫救护车', romanization: 'Jiào jiùhùchē' },
        { id: 'zh_e7', english: 'I need help', native: '我需要帮助', romanization: 'Wǒ xūyào bāngzhù' },
        { id: 'zh_e8', english: 'Fire!', native: '着火了！', romanization: 'Zháohuǒ le!' },
      ],
      shopping: [
        { id: 'zh_s1', english: 'How much is this?', native: '这个多少钱?', romanization: 'Zhège duōshǎo qián?' },
        { id: 'zh_s2', english: 'Too expensive', native: '太贵了', romanization: 'Tài guì le' },
        { id: 'zh_s3', english: 'Can you give a discount?', native: '可以打折吗?', romanization: 'Kěyǐ dǎzhé ma?' },
        { id: 'zh_s4', english: 'I\'ll take this', native: '我要这个', romanization: 'Wǒ yào zhège' },
        { id: 'zh_s5', english: 'Do you accept credit cards?', native: '可以刷卡吗?', romanization: 'Kěyǐ shuā kǎ ma?' },
        { id: 'zh_s6', english: 'I\'m just looking', native: '我只是看看', romanization: 'Wǒ zhǐshì kàn kàn' },
        { id: 'zh_s7', english: 'Can I try this on?', native: '我可以试穿吗?', romanization: 'Wǒ kěyǐ shì chuān ma?' },
        { id: 'zh_s8', english: 'Do you have smaller size?', native: '有小一点的尺码吗?', romanization: 'Yǒu xiǎo yīdiǎn de chǐmǎ ma?' },
      ],
      hotel: [
        { id: 'zh_h1', english: 'I have a reservation', native: '我有预订', romanization: 'Wǒ yǒu yùdìng' },
        { id: 'zh_h2', english: 'What time is check-out?', native: '几点退房?', romanization: 'Jǐ diǎn tuì fáng?' },
        { id: 'zh_h3', english: 'Can I have extra towels?', native: '可以再给我一些毛巾吗?', romanization: 'Kěyǐ zài gěi wǒ yīxiē máojīn ma?' },
        { id: 'zh_h4', english: 'Is breakfast included?', native: '含早餐吗?', romanization: 'Hán zǎocān ma?' },
        { id: 'zh_h5', english: 'Do you have WiFi?', native: '有WiFi吗?', romanization: 'Yǒu WiFi ma?' },
        { id: 'zh_h6', english: 'Room service please', native: '请送餐到房间', romanization: 'Qǐng sòng cān dào fángjiān' },
        { id: 'zh_h7', english: 'Can you call me a taxi?', native: '可以帮我叫出租车吗?', romanization: 'Kěyǐ bāng wǒ jiào chūzūchē ma?' },
        { id: 'zh_h8', english: 'The hot water is not working', native: '热水不出来', romanization: 'Rè shuǐ bù chūlái' },
      ],
    },
  },
};

export const LANGUAGE_LIST = Object.values(PHRASES_DATA).map(({ code, name, flag }) => ({ code, name, flag }));
